<?php

namespace Database\Seeders;

use App\Models\RecipeCatalog;
use Illuminate\Database\Seeder;

class RecipeCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = $this->getRecipes();
        
        foreach ($recipes as $recipe) {
            RecipeCatalog::firstOrCreate(
                ['name' => $recipe['name']],
                $recipe
            );
        }
    }

    private function getRecipes(): array
    {
        return array_merge(
            $this->getBreakfastRecipes(),
            $this->getLunchRecipes(),
            $this->getDinnerRecipes(),
            $this->getSnackRecipes(),
            $this->getDessertRecipes(),
            $this->getDrinkRecipes()
        );
    }

    private function getBreakfastRecipes(): array
    {
        return [
            [
                'name' => 'Avena con Frutas',
                'description' => 'Avena cremosa con frutas frescas y miel',
                'recipe' => '1. Cocina 1 taza de avena con 2 tazas de leche. 2. Agrega frutas frescas (fresas, plátano, arándanos). 3. Endulza con miel al gusto.',
                'type' => 'breakfast',
                'ingredients' => ['avena', 'leche', 'fresas', 'plátano', 'miel'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 350,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tostadas con Aguacate',
                'description' => 'Tostadas integrales con aguacate, tomate y huevo',
                'recipe' => '1. Tuesta 2 rebanadas de pan integral. 2. Machaca 1 aguacate. 3. Agrega tomate en rodajas. 4. Cocina 1 huevo frito o pochado.',
                'type' => 'breakfast',
                'ingredients' => ['pan integral', 'aguacate', 'tomate', 'huevo', 'sal', 'pimienta'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Smoothie Bowl',
                'description' => 'Bowl de smoothie con granola y frutas',
                'recipe' => '1. Licúa 1 plátano, 1 taza de fresas y 1/2 taza de yogur. 2. Vierte en un bowl. 3. Decora con granola, frutas y semillas.',
                'type' => 'breakfast',
                'ingredients' => ['plátano', 'fresas', 'yogur', 'granola', 'semillas'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pancakes de Avena',
                'description' => 'Pancakes saludables de avena y plátano',
                'recipe' => '1. Mezcla 1 plátano machacado, 2 huevos, 1/2 taza de avena. 2. Cocina en sartén antiadherente. 3. Sirve con miel o frutas.',
                'type' => 'breakfast',
                'ingredients' => ['plátano', 'huevos', 'avena', 'miel'],
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Yogur con Granola',
                'description' => 'Yogur griego con granola casera y frutos secos',
                'recipe' => '1. Sirve 1 taza de yogur griego. 2. Agrega granola al gusto. 3. Decora con frutos secos y miel.',
                'type' => 'breakfast',
                'ingredients' => ['yogur griego', 'granola', 'frutos secos', 'miel'],
                'prep_time' => 3,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Huevos Revueltos con Espinacas',
                'description' => 'Huevos revueltos con espinacas y queso',
                'recipe' => '1. Saltea espinacas en aceite. 2. Agrega 2 huevos batidos. 3. Revuelve y agrega queso. 4. Sirve caliente.',
                'type' => 'breakfast',
                'ingredients' => ['huevos', 'espinacas', 'queso', 'aceite', 'sal'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 290,
                'is_predefined' => true,
            ],
            [
                'name' => 'Chilaquiles',
                'description' => 'Tortillas fritas con salsa y huevo',
                'recipe' => '1. Fríe tortillas cortadas en triángulos. 2. Agrega salsa de tomate. 3. Cocina 2 huevos estrellados. 4. Sirve con crema y queso.',
                'type' => 'breakfast',
                'ingredients' => ['tortillas', 'salsa', 'huevos', 'crema', 'queso'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 450,
                'is_predefined' => true,
            ],
            [
                'name' => 'Waffles',
                'description' => 'Waffles caseros con miel y frutas',
                'recipe' => '1. Mezcla harina, huevos, leche y mantequilla. 2. Cocina en wafflera. 3. Sirve con miel y frutas frescas.',
                'type' => 'breakfast',
                'ingredients' => ['harina', 'huevos', 'leche', 'mantequilla', 'miel', 'frutas'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Omelette de Verduras',
                'description' => 'Omelette relleno de verduras frescas',
                'recipe' => '1. Bate 3 huevos. 2. Saltea verduras (pimiento, cebolla, champiñones). 3. Vierte huevos y cocina. 4. Dobla y sirve.',
                'type' => 'breakfast',
                'ingredients' => ['huevos', 'pimiento', 'cebolla', 'champiñones', 'queso'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'medium',
                'category' => 'saludable',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Cereal con Leche',
                'description' => 'Cereal integral con leche y frutas',
                'recipe' => '1. Vierte cereal en un bowl. 2. Agrega leche fría. 3. Decora con frutas frescas.',
                'type' => 'breakfast',
                'ingredients' => ['cereal', 'leche', 'frutas'],
                'prep_time' => 2,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'French Toast',
                'description' => 'Pan tostado francés con canela y miel',
                'recipe' => '1. Bate huevos con leche y canela. 2. Remoja pan en la mezcla. 3. Fríe hasta dorar. 4. Sirve con miel o jarabe.',
                'type' => 'breakfast',
                'ingredients' => ['pan', 'huevos', 'leche', 'canela', 'miel'],
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'postre',
                'calories' => 350,
                'is_predefined' => true,
            ],
            [
                'name' => 'Bagel con Queso Crema',
                'description' => 'Bagel tostado con queso crema y salmón',
                'recipe' => '1. Tuesta un bagel. 2. Unta queso crema. 3. Agrega salmón ahumado y alcaparras.',
                'type' => 'breakfast',
                'ingredients' => ['bagel', 'queso crema', 'salmón', 'alcaparras'],
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Huevo',
                'description' => 'Tortillas con huevo revuelto y salsas',
                'recipe' => '1. Cocina huevos revueltos. 2. Calienta tortillas. 3. Rellena con huevo, agrega salsas y cilantro.',
                'type' => 'breakfast',
                'ingredients' => ['huevos', 'tortillas', 'salsas', 'cilantro'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Muffins de Arándanos',
                'description' => 'Muffins caseros con arándanos frescos',
                'recipe' => '1. Mezcla harina, azúcar, huevos y leche. 2. Agrega arándanos. 3. Hornea a 180°C por 20 minutos.',
                'type' => 'breakfast',
                'ingredients' => ['harina', 'azúcar', 'huevos', 'leche', 'arándanos'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 12,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 220,
                'is_predefined' => true,
            ],
            [
                'name' => 'Bowl de Acai',
                'description' => 'Bowl de acai con frutas y granola',
                'recipe' => '1. Licúa acai congelado con plátano. 2. Vierte en bowl. 3. Decora con granola, coco y frutas.',
                'type' => 'breakfast',
                'ingredients' => ['acai', 'plátano', 'granola', 'coco', 'frutas'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 350,
                'is_predefined' => true,
            ],
        ];
    }

    private function getLunchRecipes(): array
    {
        return [
            [
                'name' => 'Ensalada César',
                'description' => 'Ensalada fresca con pollo y aderezo césar',
                'recipe' => '1. Mezcla lechuga, pollo asado, crutones y parmesano. 2. Agrega aderezo césar. 3. Mezcla y sirve.',
                'type' => 'lunch',
                'ingredients' => ['lechuga', 'pollo', 'crutones', 'parmesano', 'aderezo césar'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta Carbonara',
                'description' => 'Pasta cremosa con tocino y queso',
                'recipe' => '1. Cocina pasta al dente. 2. Fríe tocino. 3. Mezcla con huevos, queso parmesano y crema. 4. Sirve caliente.',
                'type' => 'lunch',
                'ingredients' => ['pasta', 'tocino', 'huevos', 'parmesano', 'crema'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 580,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Pollo',
                'description' => 'Tacos con pollo asado y vegetales',
                'recipe' => '1. Cocina pollo con especias. 2. Calienta tortillas. 3. Rellena con pollo, lechuga, tomate y salsa.',
                'type' => 'lunch',
                'ingredients' => ['pollo', 'tortillas', 'lechuga', 'tomate', 'salsa'],
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Sándwich Club',
                'description' => 'Sándwich triple con pollo, tocino y vegetales',
                'recipe' => '1. Tuesta pan. 2. Agrega pollo, tocino, lechuga, tomate y mayonesa. 3. Corta en triángulos.',
                'type' => 'lunch',
                'ingredients' => ['pan', 'pollo', 'tocino', 'lechuga', 'tomate', 'mayonesa'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 520,
                'is_predefined' => true,
            ],
            [
                'name' => 'Sopa de Pollo',
                'description' => 'Sopa casera de pollo con verduras',
                'recipe' => '1. Cocina pollo en caldo. 2. Agrega zanahoria, apio y cebolla. 3. Cocina hasta que las verduras estén tiernas. 4. Agrega fideos.',
                'type' => 'lunch',
                'ingredients' => ['pollo', 'caldo', 'zanahoria', 'apio', 'cebolla', 'fideos'],
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 6,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pizza Margherita',
                'description' => 'Pizza clásica con tomate, mozzarella y albahaca',
                'recipe' => '1. Estira masa de pizza. 2. Agrega salsa de tomate. 3. Cubre con mozzarella. 4. Hornea a 220°C por 12 minutos. 5. Agrega albahaca fresca.',
                'type' => 'lunch',
                'ingredients' => ['masa pizza', 'salsa tomate', 'mozzarella', 'albahaca'],
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Burrito de Frijoles',
                'description' => 'Burrito con frijoles, arroz y vegetales',
                'recipe' => '1. Calienta tortilla grande. 2. Agrega frijoles refritos, arroz, lechuga, tomate y queso. 3. Enrolla y sirve.',
                'type' => 'lunch',
                'ingredients' => ['tortilla', 'frijoles', 'arroz', 'lechuga', 'tomate', 'queso'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'vegana',
                'calories' => 450,
                'is_predefined' => true,
            ],
            [
                'name' => 'Ensalada de Quinoa',
                'description' => 'Ensalada nutritiva con quinoa y vegetales',
                'recipe' => '1. Cocina quinoa. 2. Mezcla con pepino, tomate, aguacate y cilantro. 3. Adereza con limón y aceite de oliva.',
                'type' => 'lunch',
                'ingredients' => ['quinoa', 'pepino', 'tomate', 'aguacate', 'cilantro', 'limón'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Hamburguesa Clásica',
                'description' => 'Hamburguesa con carne, queso y vegetales',
                'recipe' => '1. Cocina carne molida. 2. Tuesta pan. 3. Arma hamburguesa con carne, queso, lechuga, tomate y mayonesa.',
                'type' => 'lunch',
                'ingredients' => ['carne molida', 'pan hamburguesa', 'queso', 'lechuga', 'tomate', 'mayonesa'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 580,
                'is_predefined' => true,
            ],
            [
                'name' => 'Ramen',
                'description' => 'Sopa de ramen con fideos y vegetales',
                'recipe' => '1. Cocina fideos ramen. 2. Prepara caldo. 3. Agrega huevo cocido, cebollín y algas. 4. Sirve caliente.',
                'type' => 'lunch',
                'ingredients' => ['fideos ramen', 'caldo', 'huevo', 'cebollín', 'algas'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'medium',
                'category' => 'asiática',
                'calories' => 480,
                'is_predefined' => true,
            ],
            [
                'name' => 'Wrap de Pollo',
                'description' => 'Wrap con pollo, vegetales y aderezo',
                'recipe' => '1. Cocina pollo con especias. 2. Calienta tortilla de harina. 3. Rellena con pollo, lechuga, tomate y aderezo. 4. Enrolla.',
                'type' => 'lunch',
                'ingredients' => ['pollo', 'tortilla harina', 'lechuga', 'tomate', 'aderezo'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta con Salsa de Tomate',
                'description' => 'Pasta simple con salsa de tomate casera',
                'recipe' => '1. Cocina pasta. 2. Prepara salsa de tomate con ajo y albahaca. 3. Mezcla y sirve con parmesano.',
                'type' => 'lunch',
                'ingredients' => ['pasta', 'tomates', 'ajo', 'albahaca', 'parmesano'],
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'italiana',
                'calories' => 350,
                'is_predefined' => true,
            ],
            [
                'name' => 'Ensalada de Atún',
                'description' => 'Ensalada fresca con atún y vegetales',
                'recipe' => '1. Mezcla atún con mayonesa. 2. Agrega lechuga, tomate, cebolla y maíz. 3. Adereza y sirve.',
                'type' => 'lunch',
                'ingredients' => ['atún', 'mayonesa', 'lechuga', 'tomate', 'cebolla', 'maíz'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Pescado',
                'description' => 'Tacos con pescado empanizado y col',
                'recipe' => '1. Empaniza pescado. 2. Fríe hasta dorar. 3. Calienta tortillas. 4. Rellena con pescado, col y salsa.',
                'type' => 'lunch',
                'ingredients' => ['pescado', 'harina', 'tortillas', 'col', 'salsa'],
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Bowl de Poke',
                'description' => 'Bowl hawaiano con salmón y vegetales',
                'recipe' => '1. Corta salmón en cubos. 2. Prepara arroz. 3. Agrega aguacate, pepino, algas y sésamo. 4. Sirve con salsa de soja.',
                'type' => 'lunch',
                'ingredients' => ['salmón', 'arroz', 'aguacate', 'pepino', 'algas', 'sésamo'],
                'prep_time' => 20,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'medium',
                'category' => 'saludable',
                'calories' => 480,
                'is_predefined' => true,
            ],
            [
                'name' => 'Lasagna',
                'description' => 'Lasagna casera con carne y queso',
                'recipe' => '1. Prepara salsa de carne. 2. Arma capas de pasta, salsa y queso. 3. Hornea a 180°C por 45 minutos.',
                'type' => 'lunch',
                'ingredients' => ['pasta lasagna', 'carne molida', 'salsa tomate', 'queso', 'bechamel'],
                'prep_time' => 30,
                'cook_time' => 45,
                'servings' => 8,
                'difficulty' => 'hard',
                'category' => 'italiana',
                'calories' => 520,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pad Thai',
                'description' => 'Fideos tailandeses con vegetales y salsa',
                'recipe' => '1. Cocina fideos de arroz. 2. Saltea vegetales. 3. Agrega salsa pad thai. 4. Mezcla y sirve con cacahuates.',
                'type' => 'lunch',
                'ingredients' => ['fideos arroz', 'vegetales', 'salsa pad thai', 'cacahuates', 'huevo'],
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'asiática',
                'calories' => 450,
                'is_predefined' => true,
            ],
            [
                'name' => 'Ensalada de Pollo',
                'description' => 'Ensalada con pollo asado y aderezo',
                'recipe' => '1. Asa pollo. 2. Mezcla con lechuga, tomate, aguacate y maíz. 3. Adereza y sirve.',
                'type' => 'lunch',
                'ingredients' => ['pollo', 'lechuga', 'tomate', 'aguacate', 'maíz', 'aderezo'],
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Sushi Rolls',
                'description' => 'Rollos de sushi con salmón y aguacate',
                'recipe' => '1. Prepara arroz para sushi. 2. Extiende sobre alga nori. 3. Agrega salmón y aguacate. 4. Enrolla y corta.',
                'type' => 'lunch',
                'ingredients' => ['arroz sushi', 'alga nori', 'salmón', 'aguacate'],
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'hard',
                'category' => 'asiática',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Quesadillas',
                'description' => 'Quesadillas con queso y pollo',
                'recipe' => '1. Calienta tortillas. 2. Agrega queso y pollo. 3. Dobla y cocina hasta que el queso se derrita.',
                'type' => 'lunch',
                'ingredients' => ['tortillas', 'queso', 'pollo'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 420,
                'is_predefined' => true,
            ],
        ];
    }

    private function getDinnerRecipes(): array
    {
        return [
            [
                'name' => 'Salmón a la Plancha',
                'description' => 'Salmón con vegetales asados',
                'recipe' => '1. Sazona salmón. 2. Cocina a la plancha 4 minutos por lado. 3. Sirve con vegetales asados.',
                'type' => 'dinner',
                'ingredients' => ['salmón', 'limón', 'hierbas', 'vegetales'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pollo al Horno',
                'description' => 'Pollo asado con papas y vegetales',
                'recipe' => '1. Sazona pollo. 2. Hornea a 200°C por 45 minutos. 3. Agrega papas y vegetales. 4. Cocina hasta dorar.',
                'type' => 'dinner',
                'ingredients' => ['pollo', 'papas', 'vegetales', 'hierbas'],
                'prep_time' => 15,
                'cook_time' => 60,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 450,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta Alfredo',
                'description' => 'Pasta con salsa cremosa de queso',
                'recipe' => '1. Cocina pasta. 2. Prepara salsa con mantequilla, crema y parmesano. 3. Mezcla y sirve.',
                'type' => 'dinner',
                'ingredients' => ['pasta', 'mantequilla', 'crema', 'parmesano'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'italiana',
                'calories' => 520,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Carne Asada',
                'description' => 'Tacos con carne asada y salsas',
                'recipe' => '1. Asa carne. 2. Calienta tortillas. 3. Rellena con carne, cebolla, cilantro y salsas.',
                'type' => 'dinner',
                'ingredients' => ['carne', 'tortillas', 'cebolla', 'cilantro', 'salsas'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Risotto de Champiñones',
                'description' => 'Risotto cremoso con champiñones',
                'recipe' => '1. Saltea champiñones. 2. Cocina arroz agregando caldo poco a poco. 3. Agrega queso parmesano. 4. Sirve caliente.',
                'type' => 'dinner',
                'ingredients' => ['arroz arborio', 'champiñones', 'caldo', 'parmesano', 'vino blanco'],
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Enchiladas',
                'description' => 'Enchiladas con pollo y queso',
                'recipe' => '1. Rellena tortillas con pollo. 2. Enrolla y coloca en molde. 3. Cubre con salsa y queso. 4. Hornea a 180°C por 25 minutos.',
                'type' => 'dinner',
                'ingredients' => ['tortillas', 'pollo', 'salsa', 'queso'],
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 6,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 450,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pescado a la Veracruzana',
                'description' => 'Pescado con salsa de tomate y aceitunas',
                'recipe' => '1. Cocina pescado. 2. Prepara salsa con tomate, cebolla, aceitunas y alcaparras. 3. Vierte sobre pescado y cocina.',
                'type' => 'dinner',
                'ingredients' => ['pescado', 'tomate', 'cebolla', 'aceitunas', 'alcaparras'],
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta con Camarones',
                'description' => 'Pasta con camarones y ajo',
                'recipe' => '1. Cocina pasta. 2. Saltea camarones con ajo. 3. Agrega vino blanco y hierbas. 4. Mezcla con pasta.',
                'type' => 'dinner',
                'ingredients' => ['pasta', 'camarones', 'ajo', 'vino blanco', 'hierbas'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Chiles Rellenos',
                'description' => 'Chiles poblanos rellenos de queso',
                'recipe' => '1. Asa chiles. 2. Rellena con queso. 3. Empaniza. 4. Fríe hasta dorar. 5. Sirve con salsa de tomate.',
                'type' => 'dinner',
                'ingredients' => ['chiles poblanos', 'queso', 'huevos', 'harina', 'salsa tomate'],
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'hard',
                'category' => 'tradicional',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pollo Teriyaki',
                'description' => 'Pollo con salsa teriyaki y arroz',
                'recipe' => '1. Cocina pollo. 2. Prepara salsa teriyaki. 3. Cocina arroz. 4. Sirve pollo con salsa sobre arroz.',
                'type' => 'dinner',
                'ingredients' => ['pollo', 'salsa teriyaki', 'arroz', 'vegetales'],
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'asiática',
                'calories' => 450,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Camarón',
                'description' => 'Tacos con camarones y col',
                'recipe' => '1. Cocina camarones con especias. 2. Calienta tortillas. 3. Rellena con camarones, col y salsa.',
                'type' => 'dinner',
                'ingredients' => ['camarones', 'tortillas', 'col', 'salsa', 'limón'],
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta Puttanesca',
                'description' => 'Pasta con salsa de tomate, aceitunas y anchoas',
                'recipe' => '1. Cocina pasta. 2. Prepara salsa con tomate, aceitunas, anchoas y alcaparras. 3. Mezcla y sirve.',
                'type' => 'dinner',
                'ingredients' => ['pasta', 'tomate', 'aceitunas', 'anchoas', 'alcaparras'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'italiana',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Mole Poblano',
                'description' => 'Pollo con mole poblano y arroz',
                'recipe' => '1. Cocina pollo. 2. Prepara mole con chiles y especias. 3. Cocina arroz. 4. Sirve pollo bañado en mole.',
                'type' => 'dinner',
                'ingredients' => ['pollo', 'mole', 'chiles', 'especias', 'arroz'],
                'prep_time' => 30,
                'cook_time' => 60,
                'servings' => 6,
                'difficulty' => 'hard',
                'category' => 'tradicional',
                'calories' => 520,
                'is_predefined' => true,
            ],
            [
                'name' => 'Salmón Teriyaki',
                'description' => 'Salmón con salsa teriyaki y vegetales',
                'recipe' => '1. Cocina salmón. 2. Prepara salsa teriyaki. 3. Saltea vegetales. 4. Sirve salmón con salsa y vegetales.',
                'type' => 'dinner',
                'ingredients' => ['salmón', 'salsa teriyaki', 'vegetales'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'asiática',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta Aglio e Olio',
                'description' => 'Pasta simple con ajo y aceite de oliva',
                'recipe' => '1. Cocina pasta. 2. Saltea ajo en aceite de oliva. 3. Agrega perejil. 4. Mezcla con pasta.',
                'type' => 'dinner',
                'ingredients' => ['pasta', 'ajo', 'aceite oliva', 'perejil'],
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'italiana',
                'calories' => 350,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Lengua',
                'description' => 'Tacos con lengua de res',
                'recipe' => '1. Cocina lengua hasta que esté tierna. 2. Corta en trozos. 3. Calienta tortillas. 4. Rellena con lengua, cebolla y cilantro.',
                'type' => 'dinner',
                'ingredients' => ['lengua', 'tortillas', 'cebolla', 'cilantro', 'salsas'],
                'prep_time' => 10,
                'cook_time' => 120,
                'servings' => 6,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 380,
                'is_predefined' => true,
            ],
        ];
    }

    private function getSnackRecipes(): array
    {
        return [
            [
                'name' => 'Hummus con Vegetales',
                'description' => 'Hummus casero con vegetales frescos',
                'recipe' => '1. Licúa garbanzos, tahini, limón y ajo. 2. Sirve con zanahorias, apio y pepino.',
                'type' => 'snack',
                'ingredients' => ['garbanzos', 'tahini', 'limón', 'ajo', 'vegetales'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 180,
                'is_predefined' => true,
            ],
            [
                'name' => 'Palomitas',
                'description' => 'Palomitas de maíz caseras',
                'recipe' => '1. Calienta aceite en sartén. 2. Agrega maíz. 3. Tapa y cocina hasta que dejen de explotar. 4. Sazona al gusto.',
                'type' => 'snack',
                'ingredients' => ['maíz palomero', 'aceite', 'sal'],
                'prep_time' => 2,
                'cook_time' => 5,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 120,
                'is_predefined' => true,
            ],
            [
                'name' => 'Mix de Frutos Secos',
                'description' => 'Mezcla de frutos secos y semillas',
                'recipe' => '1. Mezcla almendras, nueces, cacahuates y semillas. 2. Tuesta ligeramente. 3. Agrega pasas si deseas.',
                'type' => 'snack',
                'ingredients' => ['almendras', 'nueces', 'cacahuates', 'semillas'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Yogur con Frutas',
                'description' => 'Yogur con frutas frescas',
                'recipe' => '1. Sirve yogur en un bowl. 2. Agrega frutas frescas. 3. Endulza con miel si deseas.',
                'type' => 'snack',
                'ingredients' => ['yogur', 'frutas', 'miel'],
                'prep_time' => 3,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 150,
                'is_predefined' => true,
            ],
            [
                'name' => 'Nachos',
                'description' => 'Nachos con queso y jalapeños',
                'recipe' => '1. Coloca totopos en plato. 2. Agrega queso derretido. 3. Decora con jalapeños y crema.',
                'type' => 'snack',
                'ingredients' => ['totopos', 'queso', 'jalapeños', 'crema'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 420,
                'is_predefined' => true,
            ],
        ];
    }

    private function getDessertRecipes(): array
    {
        return [
            [
                'name' => 'Brownies',
                'description' => 'Brownies de chocolate caseros',
                'recipe' => '1. Mezcla chocolate, mantequilla, azúcar y huevos. 2. Agrega harina. 3. Hornea a 180°C por 25 minutos.',
                'type' => 'dessert',
                'ingredients' => ['chocolate', 'mantequilla', 'azúcar', 'huevos', 'harina'],
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 12,
                'difficulty' => 'easy',
                'category' => 'postre',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Cheesecake',
                'description' => 'Pastel de queso cremoso',
                'recipe' => '1. Prepara base de galletas. 2. Mezcla queso crema, azúcar y huevos. 3. Hornea a 160°C por 60 minutos.',
                'type' => 'dessert',
                'ingredients' => ['galletas', 'queso crema', 'azúcar', 'huevos', 'crema agria'],
                'prep_time' => 30,
                'cook_time' => 60,
                'servings' => 12,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Flan',
                'description' => 'Flan casero de vainilla',
                'recipe' => '1. Prepara caramelo. 2. Mezcla leche, huevos, azúcar y vainilla. 3. Cocina a baño maría por 60 minutos.',
                'type' => 'dessert',
                'ingredients' => ['leche', 'huevos', 'azúcar', 'vainilla'],
                'prep_time' => 15,
                'cook_time' => 60,
                'servings' => 8,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 220,
                'is_predefined' => true,
            ],
            [
                'name' => 'Helado de Vainilla',
                'description' => 'Helado casero de vainilla',
                'recipe' => '1. Mezcla leche, crema, azúcar y vainilla. 2. Congela en máquina de helados. 3. Sirve frío.',
                'type' => 'dessert',
                'ingredients' => ['leche', 'crema', 'azúcar', 'vainilla'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 8,
                'difficulty' => 'easy',
                'category' => 'postre',
                'calories' => 250,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tres Leches',
                'description' => 'Pastel de tres leches',
                'recipe' => '1. Hornea pastel. 2. Mezcla leche evaporada, condensada y crema. 3. Vierte sobre pastel. 4. Decora con crema batida.',
                'type' => 'dessert',
                'ingredients' => ['harina', 'huevos', 'azúcar', 'leche evaporada', 'leche condensada', 'crema'],
                'prep_time' => 30,
                'cook_time' => 30,
                'servings' => 12,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Churros',
                'description' => 'Churros caseros con azúcar y canela',
                'recipe' => '1. Prepara masa de churros. 2. Fríe en aceite caliente. 3. Espolvorea con azúcar y canela.',
                'type' => 'dessert',
                'ingredients' => ['harina', 'agua', 'mantequilla', 'azúcar', 'canela'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 6,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pay de Limón',
                'description' => 'Pay de limón con base de galleta',
                'recipe' => '1. Prepara base de galleta. 2. Mezcla leche condensada, limón y yemas. 3. Vierte y hornea. 4. Decora con merengue.',
                'type' => 'dessert',
                'ingredients' => ['galletas', 'mantequilla', 'leche condensada', 'limón', 'huevos'],
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 10,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 350,
                'is_predefined' => true,
            ],
            [
                'name' => 'Galletas de Chocolate',
                'description' => 'Galletas caseras con chispas de chocolate',
                'recipe' => '1. Mezcla mantequilla, azúcar, huevos y harina. 2. Agrega chispas de chocolate. 3. Hornea a 180°C por 12 minutos.',
                'type' => 'dessert',
                'ingredients' => ['mantequilla', 'azúcar', 'huevos', 'harina', 'chispas chocolate'],
                'prep_time' => 15,
                'cook_time' => 12,
                'servings' => 24,
                'difficulty' => 'easy',
                'category' => 'postre',
                'calories' => 180,
                'is_predefined' => true,
            ],
        ];
    }

    private function getDrinkRecipes(): array
    {
        return [
            [
                'name' => 'Agua de Horchata',
                'description' => 'Agua fresca de horchata',
                'recipe' => '1. Licúa arroz con canela. 2. Cuela. 3. Agrega leche, azúcar y vainilla. 4. Sirve frío.',
                'type' => 'drink',
                'ingredients' => ['arroz', 'canela', 'leche', 'azúcar', 'vainilla'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 6,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 120,
                'is_predefined' => true,
            ],
            [
                'name' => 'Limonada',
                'description' => 'Limonada fresca casera',
                'recipe' => '1. Exprime limones. 2. Agrega azúcar y agua. 3. Mezcla bien. 4. Sirve con hielo.',
                'type' => 'drink',
                'ingredients' => ['limones', 'azúcar', 'agua', 'hielo'],
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 80,
                'is_predefined' => true,
            ],
            [
                'name' => 'Smoothie de Fresa',
                'description' => 'Smoothie cremoso de fresa',
                'recipe' => '1. Licúa fresas, plátano, yogur y miel. 2. Agrega hielo. 3. Licúa hasta que esté suave.',
                'type' => 'drink',
                'ingredients' => ['fresas', 'plátano', 'yogur', 'miel', 'hielo'],
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 180,
                'is_predefined' => true,
            ],
            [
                'name' => 'Café Latte',
                'description' => 'Café con leche espumada',
                'recipe' => '1. Prepara espresso. 2. Calienta leche. 3. Espuma la leche. 4. Vierte sobre café.',
                'type' => 'drink',
                'ingredients' => ['café', 'leche'],
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 120,
                'is_predefined' => true,
            ],
            [
                'name' => 'Té de Manzanilla',
                'description' => 'Té relajante de manzanilla',
                'recipe' => '1. Hierve agua. 2. Agrega bolsita de manzanilla. 3. Deja reposar 5 minutos. 4. Endulza al gusto.',
                'type' => 'drink',
                'ingredients' => ['agua', 'manzanilla', 'miel'],
                'prep_time' => 2,
                'cook_time' => 5,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 5,
                'is_predefined' => true,
            ],
            [
                'name' => 'Agua de Jamaica',
                'description' => 'Agua fresca de flor de jamaica',
                'recipe' => '1. Hierve flor de jamaica. 2. Cuela. 3. Agrega azúcar. 4. Enfría y sirve.',
                'type' => 'drink',
                'ingredients' => ['flor jamaica', 'azúcar', 'agua'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 100,
                'is_predefined' => true,
            ],
            [
                'name' => 'Batido de Proteína',
                'description' => 'Batido nutritivo con proteína',
                'recipe' => '1. Licúa leche, plátano, proteína en polvo y mantequilla de maní. 2. Agrega hielo. 3. Licúa hasta suave.',
                'type' => 'drink',
                'ingredients' => ['leche', 'plátano', 'proteína', 'mantequilla maní', 'hielo'],
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Chocolate Caliente',
                'description' => 'Chocolate caliente cremoso',
                'recipe' => '1. Calienta leche. 2. Agrega chocolate y azúcar. 3. Mezcla hasta disolver. 4. Sirve caliente.',
                'type' => 'drink',
                'ingredients' => ['leche', 'chocolate', 'azúcar', 'canela'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'postre',
                'calories' => 250,
                'is_predefined' => true,
            ],

            // Recetas adicionales - Desayunos
            [
                'name' => 'Pancakes de Avena',
                'description' => 'Pancakes saludables con avena',
                'recipe' => '1. Mezcla avena, huevos, leche y plátano. 2. Cocina en sartén. 3. Sirve con miel.',
                'type' => 'breakfast',
                'ingredients' => ['avena', 'huevos', 'leche', 'plátano', 'miel'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Smoothie Bowl',
                'description' => 'Bowl de smoothie con frutas',
                'recipe' => '1. Licúa frutas congeladas. 2. Vierte en bowl. 3. Decora con granola y frutas frescas.',
                'type' => 'breakfast',
                'ingredients' => ['frutas congeladas', 'yogur', 'granola', 'frutas frescas'],
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tostadas Francesas',
                'description' => 'Tostadas francesas con canela',
                'recipe' => '1. Bate huevos con leche y canela. 2. Remoja pan. 3. Cocina en sartén hasta dorar.',
                'type' => 'breakfast',
                'ingredients' => ['pan', 'huevos', 'leche', 'canela', 'mantequilla'],
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'tradicional',
                'calories' => 350,
                'is_predefined' => true,
            ],

            // Recetas adicionales - Almuerzos
            [
                'name' => 'Ensalada César',
                'description' => 'Ensalada César clásica',
                'recipe' => '1. Mezcla lechuga, crutones y parmesano. 2. Prepara aderezo César. 3. Mezcla y sirve.',
                'type' => 'lunch',
                'ingredients' => ['lechuga', 'crutones', 'parmesano', 'pollo', 'aderezo'],
                'prep_time' => 15,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Wrap de Pollo',
                'description' => 'Wrap con pollo y vegetales',
                'recipe' => '1. Cocina pollo. 2. Calienta tortilla. 3. Rellena con pollo, vegetales y aderezo. 4. Enrolla.',
                'type' => 'lunch',
                'ingredients' => ['tortilla', 'pollo', 'lechuga', 'tomate', 'aderezo'],
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'category' => 'rápida',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Sopa de Lentejas',
                'description' => 'Sopa nutritiva de lentejas',
                'recipe' => '1. Sofríe cebolla y ajo. 2. Agrega lentejas y caldo. 3. Cocina hasta suave. 4. Sirve caliente.',
                'type' => 'lunch',
                'ingredients' => ['lentejas', 'cebolla', 'ajo', 'caldo', 'zanahoria'],
                'prep_time' => 10,
                'cook_time' => 40,
                'servings' => 6,
                'difficulty' => 'easy',
                'category' => 'saludable',
                'calories' => 250,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pizza Margherita',
                'description' => 'Pizza clásica italiana',
                'recipe' => '1. Estira masa. 2. Agrega salsa, mozzarella y albahaca. 3. Hornea a 220°C por 12 minutos.',
                'type' => 'lunch',
                'ingredients' => ['masa pizza', 'salsa tomate', 'mozzarella', 'albahaca'],
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 320,
                'is_predefined' => true,
            ],

            // Recetas adicionales - Cenas
            [
                'name' => 'Salmón a la Plancha',
                'description' => 'Salmón con vegetales asados',
                'recipe' => '1. Marina salmón. 2. Cocina a la plancha. 3. Asa vegetales. 4. Sirve junto.',
                'type' => 'dinner',
                'ingredients' => ['salmón', 'limón', 'hierbas', 'vegetales'],
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'saludable',
                'calories' => 350,
                'is_predefined' => true,
            ],
            [
                'name' => 'Risotto de Champiñones',
                'description' => 'Risotto cremoso con champiñones',
                'recipe' => '1. Sofríe champiñones. 2. Cocina arroz arborio con caldo. 3. Agrega champiñones y parmesano.',
                'type' => 'dinner',
                'ingredients' => ['arroz arborio', 'champiñones', 'caldo', 'parmesano', 'vino blanco'],
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 380,
                'is_predefined' => true,
            ],
            [
                'name' => 'Tacos de Pescado',
                'description' => 'Tacos con pescado empanizado',
                'recipe' => '1. Empaniza pescado. 2. Fríe hasta dorar. 3. Calienta tortillas. 4. Rellena con pescado, col y salsa.',
                'type' => 'dinner',
                'ingredients' => ['pescado', 'harina', 'huevos', 'tortillas', 'col', 'salsa'],
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 420,
                'is_predefined' => true,
            ],
            [
                'name' => 'Pasta Carbonara',
                'description' => 'Pasta con salsa carbonara',
                'recipe' => '1. Cocina pasta. 2. Sofríe panceta. 3. Mezcla huevos, queso y panceta. 4. Combina con pasta caliente.',
                'type' => 'dinner',
                'ingredients' => ['pasta', 'panceta', 'huevos', 'parmesano', 'pimienta'],
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'medium',
                'category' => 'italiana',
                'calories' => 450,
                'is_predefined' => true,
            ],

            // Recetas adicionales - Postres
            [
                'name' => 'Tarta de Limón',
                'description' => 'Tarta refrescante de limón',
                'recipe' => '1. Prepara base de galleta. 2. Rellena con crema de limón. 3. Refrigera 2 horas. 4. Decora con merengue.',
                'type' => 'dessert',
                'ingredients' => ['galletas', 'mantequilla', 'limón', 'huevos', 'azúcar'],
                'prep_time' => 30,
                'cook_time' => 0,
                'servings' => 8,
                'difficulty' => 'medium',
                'category' => 'postre',
                'calories' => 320,
                'is_predefined' => true,
            ],
            [
                'name' => 'Brownies',
                'description' => 'Brownies de chocolate',
                'recipe' => '1. Derrite chocolate y mantequilla. 2. Mezcla con azúcar, huevos y harina. 3. Hornea a 180°C por 25 minutos.',
                'type' => 'dessert',
                'ingredients' => ['chocolate', 'mantequilla', 'azúcar', 'huevos', 'harina'],
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 12,
                'difficulty' => 'easy',
                'category' => 'postre',
                'calories' => 280,
                'is_predefined' => true,
            ],
            [
                'name' => 'Flan',
                'description' => 'Flan casero tradicional',
                'recipe' => '1. Prepara caramelo. 2. Mezcla leche, huevos y azúcar. 3. Vierte en molde. 4. Cocina a baño maría por 50 minutos.',
                'type' => 'dessert',
                'ingredients' => ['leche', 'huevos', 'azúcar', 'vainilla'],
                'prep_time' => 15,
                'cook_time' => 50,
                'servings' => 8,
                'difficulty' => 'medium',
                'category' => 'tradicional',
                'calories' => 200,
                'is_predefined' => true,
            ],
            [
                'name' => 'Helado de Vainilla',
                'description' => 'Helado casero de vainilla',
                'recipe' => '1. Calienta leche con azúcar. 2. Mezcla con yemas y vainilla. 3. Enfría. 4. Congela en máquina de helado.',
                'type' => 'dessert',
                'ingredients' => ['leche', 'crema', 'azúcar', 'yemas', 'vainilla'],
                'prep_time' => 20,
                'cook_time' => 0,
                'servings' => 8,
                'difficulty' => 'hard',
                'category' => 'postre',
                'calories' => 250,
                'is_predefined' => true,
            ],
        ];
    }
}
